#include <stdio.h>
#include "hash_tables.h"

/**
 * key_index - gives a index to key
 * @key: unique number generated by hash_djb2
 * @size: size of array
 *
 * Return: index where key and value is stored
 */
unsigned long int key_index(const unsigned char *key, unsigned long int size)
{
	unsigned long int index;

	index = hash_djb2(key) % size;

	return (index);
}
